version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
  pre_build:
    commands:
      - ls -al
      - pip install --upgrade pip
      - pip install -r requirements.txt
  post_build:
    commands:
#      - pycodestyle src
#      - flake8 src
      -  python -m pytest
artifacts:
  files:
    - '**/*'
  name: myname-$(date +%Y-%m-%d) 
