version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
  pre_build:
    commands:
      - pip install < requirements.txt
artifacts:
  files:
    - '**/*'
  name: myname-$(date +%Y-%m-%d) 
      
